[package]
name = "battlebit"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = "0.4"
flexi_logger = "0.25"
num = "0.4"
num-derive = "0.4"
num-traits = "0.2"
byteorder = "1.4"
